FROM phusion/baseimage:latest

WORKDIR /opt/

#Install Dotnet
RUN 	sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list' \
	&& apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893 \
	&& apt-get update \
	&& apt-get install -y dotnet-dev-1.0.4

#Install required software
RUN     apt-get update \
	&& apt-get update \
	&& apt-get install -y git libopus0 opus-tools libopus-dev libsodium-dev ffmpeg rsync

#Download and install stable version of Nadeko
RUN curl -L https://raw.githubusercontent.com/Poag/nadeko/1.4/nadeko_installer_1_4.sh | sh \
	&& curl -L https://raw.githubusercontent.com/Poag/nadeko/1.4/nadeko_autorestart.sh > nadeko.sh \
	&& chmod 755 nadeko.sh

VOLUME ["/root/nadeko"]

CMD ["/opt/nadeko.sh"]
