#!/bin/bash

function handle_signal {
  PID=$!
  echo "received signal. PID is ${PID}"
  kill -s SIGHUP $PID
}

trap "handle_signal" SIGINT SIGTERM SIGHUP

echo "starting Nadeko"
cd /root/NadekoBot
mono NadekoBot.exe & wait
echo "stopping Nadeko"